import {
  ArrowRight, BadgeCheck, Eye, MapPin, Navigation, Plus,
  ShieldCheck, Sparkles, Star,
} from '../../fontawesome-icons'
import { peso } from '../../lib/app'

export default function RecommendationCard({ recommendation, onDetails, onAdd }) {
  const mapUrl = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(recommendation.coordinates.join(','))}`
  return <article className="group grid overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-0.5 hover:shadow-xl hover:shadow-slate-200/70 lg:grid-cols-[300px_minmax(0,1fr)]">
    <div className="relative min-h-64 overflow-hidden bg-slate-100 lg:min-h-full">{recommendation.image_url ? <img className="absolute inset-0 h-full w-full object-cover transition duration-500 group-hover:scale-105" src={recommendation.image_url} alt={recommendation.name} /> : <span className="absolute inset-0 grid place-items-center bg-gradient-to-br from-teal-50 to-blue-100 text-teal-700"><MapPin size={44} /></span>}<div className="absolute inset-0 bg-gradient-to-t from-slate-950/65 via-transparent to-transparent" /><span className="absolute left-4 top-4 rounded-full bg-white/95 px-3 py-1.5 text-xs font-extrabold text-slate-800 shadow">{recommendation.category}</span><div className="absolute right-4 top-4 flex items-center gap-1 rounded-full bg-slate-950/80 px-3 py-1.5 text-xs font-bold text-white"><Star size={13} fill="currentColor" /> {recommendation.average_rating ?? 'New'}{recommendation.review_count ? ` (${recommendation.review_count})` : ''}</div><div className="absolute inset-x-4 bottom-4 text-white"><span className="flex items-center gap-1.5 text-xs font-bold"><MapPin size={14} /> {recommendation.area}</span></div></div>
    <div className="flex min-w-0 flex-col p-5 sm:p-6">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><span className="inline-flex items-center gap-1.5 text-xs font-extrabold uppercase tracking-[0.1em] text-teal-700"><BadgeCheck size={14} /> {recommendation.match_tier}</span><h3 className="mt-2 text-2xl font-extrabold text-slate-950">{recommendation.name}</h3></div>{recommendation.match_score != null && <span className="grid size-16 shrink-0 place-items-center rounded-full border-[5px] border-teal-100 bg-teal-700 text-center text-white shadow-md"><strong className="text-lg leading-none">{recommendation.match_score}%</strong><small className="text-[9px] font-bold uppercase">match</small></span>}</div>
      <p className="mt-4 line-clamp-2 text-sm leading-6 text-slate-600">{recommendation.description}</p>
      <div className="mt-4 flex items-start gap-2 rounded-xl bg-teal-50 p-3.5 text-sm leading-6 text-teal-900"><Sparkles className="mt-0.5 shrink-0 text-teal-700" size={17} /><span>{recommendation.recommendation_reason}</span></div>
      <div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4"><span className="rounded-xl bg-slate-50 p-3"><small className="block text-[11px] font-bold uppercase tracking-wide text-slate-400">Entrance</small><strong className="mt-1 block text-sm text-slate-800">{peso.format(Number(recommendation.entrance_fee || 0))}</strong></span><span className="rounded-xl bg-slate-50 p-3"><small className="block text-[11px] font-bold uppercase tracking-wide text-slate-400">Hours</small><strong className="mt-1 block text-sm text-slate-800">{recommendation.hours}</strong></span><span className="rounded-xl bg-slate-50 p-3"><small className="block text-[11px] font-bold uppercase tracking-wide text-slate-400">Travel time</small><strong className="mt-1 block text-sm text-slate-800">{recommendation.estimated_travel_time}</strong></span><span className="rounded-xl bg-slate-50 p-3"><small className="block text-[11px] font-bold uppercase tracking-wide text-slate-400">Visit length</small><strong className="mt-1 block text-sm text-slate-800">{recommendation.visit_minutes} min</strong></span></div>
      <p className="mt-4 flex items-start gap-2 text-sm leading-6 text-slate-600"><ShieldCheck className="mt-0.5 shrink-0 text-blue-600" size={16} /><span><strong className="text-slate-800">Accessibility:</strong> {recommendation.accessibility_information}</span></p>
      <div className="mt-auto flex flex-wrap gap-2 border-t border-slate-100 pt-5"><button type="button" className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-300 bg-white px-4 text-sm font-bold text-slate-700 hover:border-teal-400 hover:bg-teal-50" onClick={() => onDetails(recommendation)}><Eye size={16} /> View Details</button><button type="button" className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-teal-700 px-4 text-sm font-bold text-white shadow-sm hover:bg-teal-800" onClick={() => onAdd(recommendation)}><Plus size={16} /> Add to Itinerary <ArrowRight size={15} /></button><a className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-300 bg-white px-4 text-sm font-bold text-slate-700 no-underline hover:border-blue-400 hover:bg-blue-50" href={mapUrl} target="_blank" rel="noreferrer"><Navigation size={16} /> View on Map</a></div>
    </div>
  </article>
}
